version: "3.8"

services:
  # application
  microservice-01-app:
    container_name: microservice-01-app
    image: devsidnei/php8.1-fpm
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - microservice-01-redis
    networks:
      - microservice-01

  #queue  
  microservice-01-queue:
    container_name: microservice-01-queue
    image: devsidnei/php8.1-fpm
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - microservice-01-redis
      - microservice-01-mariadb
    networks:
      - microservice-01

  #nginx  
  microservice-01-nginx:
    container_name: microservice-01-nginx
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - 80
      - 443
    volumes:
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    networks:
      - microservice-01

  # redis  
  microservice-01-redis:
    container_name: microservice-01-redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - microservice-01

  # mariadb  
  microservice-01-mariadb:
    container_name: microservice-01-mariadb
    image: mariadb:10.6.10
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    networks:
      - microservice-01

networks:
  microservice-01:
    name: microservice-01
